### PR TITLE
config base url fix

### PR DESCRIPTION
**Pull request by pythexcel**

### CODE REVIEW

**Comment by xmagestore** [comment]
image
make amount above than reason

**Comment by xmagestore** [comment]
image
rename Customer Transactions to Store Credit Transactions

**Comment by xmagestore** [comment]
for credits added/removed via admin automatically add "by admin" in the end of msg 
image

**Comment by gaurav-k1994** [comment]
> image
> rename Customer Transactions to Store Credit Transactions

sir, fixed this one

**Comment by gaurav-k1994** [comment]
> image
> make amount above than reason

sir, didn't get you on this point

**Comment by gaurav-k1994** [comment]
> for credits added/removed via admin automatically add "by admin" in the end of msg
> image

done

**Pull request closed without merging**
